const express = require("express");
const jwt = require("express-jwt"); // validate jwt and set req.user
const jwksRsa = require("jwks-rsa"); // retrieve RSA keys from a json web key and set (JWKS) endpoint
const checkScope = require("express-jwt-authz"); // validate jwt scopes
require("dotenv").config();

// Validates informations inside the jwt and ensure that the jwt is generated by Auth0
const checkJwt = jwt({
  // Dynamically provide a signing key based on the kid in the header
  // and the signing keys provided by the JWKS endpoint.
  secret: jwksRsa.expressJwtSecret({
    cache: true, // cache the signing key
    rateLimit: true,
    jwksRequestsPerMinute: 5, // prevent attackers from requesting more than 5 per minute
    jwksUri: `https://${process.env.REACT_APP_AUTH0_DOMAIN}/.well-known/jwks.json`,
  }),

  // Validate the audience and the issuer.
  audience: process.env.REACT_APP_AUTH0_AUDIENCE,
  issuer: `https://${process.env.REACT_APP_AUTH0_DOMAIN}/`,

  // This must match the algorithm selected in the Auth0 dashboard under your app's advanced settings under the OAuth tab
  algorithms: ["RS256"],
});

const app = express();

app.get("/public", (req, res) => {
  res.json({
    message: "Hello from public api",
  });
});

app.get("/private", checkJwt, (req, res) => {
  res.json({
    message: "Hello from private api",
  });
});
app.get("/course", checkJwt, checkScope(["read:courses"]), (req, res) => {
  res.json({
    courses: [
      { id: 1, title: "Building apps with React and Redux" },
      { id: 2, title: "JavaScript Design Patterns" },
    ],
  });
});

function checkRole(role) {
  return function (req, res, next) {
    const assignedRoles = req.user["http://localhost:3000/roles"];
    if (Array.isArray(assignedRoles) && assignedRoles.includes(role)) {
      return next();
    } else {
      return res.status(401).send("Insufficient role");
    }
  };
}

app.get("/admin", checkJwt, checkRole("admin"), (req, res) => {
  res.json({
    message: "Hello from admin API",
  });
});

app.listen(3001);
console.log("API server running on " + process.env.REACT_APP_AUTH0_AUDIENCE);
